### ISSUE TITLE
Need more text on motivation

### ISSUE THREAD

**Issue by josephlhall** [josephlhall/draft-hall-iasa2-struct#4]
From Joel Halpern, after some email discussion:

>Reading the document, I could not tell why it was being written.
>
>From your comment there appear to be two choices:
>
>1) It is putting flesh on one of the alternatives that are under consideration, so that folks can better evaluate the impact of the choice.
>
>2) It is filling in the next step in a conclusion on path that has already been reached.
>
>In either case, the document needs to say what it is doing and point at some other document to explain why.  If it is merely expolaratory, then pointing at the earlier I-Ds is probably sufficient.  I doubt that is the intent.
>
>If it is intended as the next step, then it needs to point to something to say "this is the agreement on direction, and therefore ...
>
>Note that agreement in the non-WG session in the room needs to be validated on the IETF list for IETF-wide process decisions.

**Comment by josephlhall** [comment]
Task is to add text so that his option 1 is more obvious, pointing to draft-haberman, draft-daigle, draft-arkko and draft-hall-wrkshps-report

**Comment by coopdanger** [comment]
Perhaps, but some of the feedback from the last session was to look at these organizational options first or in parallel with the legal options (see, e.g., Lucy and Jonne in the minutes). So I don't think strictly speaking this document needs to justify its existence based on previous documents.
